config/routes.rb
Sengu::Application.routes.draw do
  resources :services, except: [:show] do
    collection do
      post :search
    end

    member do
      get :template_list
    end
  end
  resources :templates, controller: "templates/templates", except: [:index, :show] do
    collection do
      post :element_relation_search_form
      post :element_relation_search

      get :change_order_form
      patch :change_order
    end

    member do
      get :data_select_upon_extension_form
      post :data_select_upon_extension
      post :data_select_upon_extension_preview
      get :download_csv_format     # CSVフォーマット出力
      get :download_description_pdf
    end

    resources :records, controller: "templates/records" do
      collection do
        get :import_csv_form      # CSV一括登録画面
        post :confirm_import_csv  # CSV一括登録確認
        post :import_csv          # CSV一括登録処理
        get :complete_import_csv  # CSV一括登録完了画面
        get :download_csv         # CSV出力
        get :download_rdf         # RDF出力

        post :search_keyword       # キーワード検索

        get :element_description # 項目の説明popover

        post :element_relation_search_form
        post :element_relation_search
        delete :remove_csv_file

        post :add_form
        post :add_namespace_form
        get :sample_field
      end

      member do
        get :display_relation_contents # 選択している関連データの表示
        get :download_file
      end
    end

    resources :elements, controller: "templates/elements", except: [:show, :index] do
      collection do
        get :show
        get :vocabulary_form
        get :other_form
        get :change_form
        get :select_other_element_form
        get :template_form
        get :sort
        patch :change_order
        get :values
        get :vocabulary_values
        get :show_elements
        get :edit_settings
        patch :update_settings
      end

      member do
        patch :move
      end
    end

    resources :settings, controller: "templates/settings", only: [] do
      collection do
        get :set_confirm_entries
        post :update_set_confirm_entries
        get :set_authority
        post :update_set_authority
      end

      member do
        get :edit_location_group
        patch :update_location_group # グループ編集
      end
    end
  end

  namespace :templates, as: :template do
    resources :maps, only: [] do
      collection do
        post :display_search # 住所検索地図表示
        get :display # 地図表示
        get :search_city_id_select # 市町村セレクトの都道府県きりかえ
        post :search_address_location # 住所検索
        get :load_content # 国土地理院の画像を表示するためのアクション
      end
    end
  end

  root to: 'services#index'

  devise_for :users, {
    controllers: {
      registrations: "users",
      sessions: "users/sessions"
    }
  }

  scope :admin, module: :admin do
    resources :regular_expressions

    namespace :vocabulary do
      resources :elements do
        resources :values, controller: "elements/values"
      end
    end
  end

  scope :user_maintenance, module: :user_maintenance do
    resources :sections do
      devise_scope :user do
        resources :users, controller: "sections/users" do
          collection do
            post :inherit_data
            get :inherit_data_form
            get :edit_password
            patch :update_password
          end
        end
      end

      resources :user_groups, controller: "sections/user_groups" do
        member do
          get :user_list
          get :template_list
          get :set_member
          post :search_member
          post :update_set_member
          delete :destroy_member
        end
      end
    end
  end

  mount Vdb::Engine => "/vdb"

end

app/controllers/templates/records_controller.rb
#
#== データ入出力管理
#
class Templates::RecordsController < ApplicationController
  include Concerns::TemplatesController

  skip_before_filter :verify_authenticity_token, only: [:search_keyword, :element_relation_search_form, :element_relation_search]

  before_action :set_template_record, only: [:show, :edit, :update, :destroy, :display_relation_contents, :download_file]

  before_action :editable_check, only: [:edit, :update]
  before_action :destroyable_check, only: [:destroy]

  layout "template_records", only: [:index, :new, :edit, :create, :update,
    :import_csv, :confirm_import_csv, :import_csv_form, :complete_import_csv]

  #=== 入力データ一覧表示画面
  #
  # GET /templates/1/records
  #
  # 登録されているデータの一覧を表示する画面
  #link:../captures/templates/records/index.png
  def index
    @elements = @template.inputable_elements{|e|e.includes(:input_type)}.select(&:display)
    @template_records = @template.all_records.includes(values: :content).page(params[:page]).order("id DESC")
  end

  #=== 入力データ詳細表示画面
  #
  # GET /templates/1/records/1
  #
  # 登録されているデータの詳細を表示する画面(Ajax modal)
  #link:../captures/templates/records/show.png
  def show
    @elements = @template.all_elements.root.availables.includes(:input_type, :source)
  end


  #=== データ作成画面
  #
  # GET /templates/1/records/new
  #
  # 作成したテンプレートをもとにデータの入力を行う画面
  #link:../captures/templates/records/new.png
  def new
    @template_record ||= @template.template_records.build
    set_form_assigns
  end


  #=== データ登録処理
  #
  # POST /templates/1/records
  #
  # データの登録処理を行う機能
  def create
    @template_record = @template.template_records.build
    @template_record.user_id = current_user.id
    begin
      ActiveRecord::Base.transaction do
        @template_record.save_from_params!(params[:template_record], @template)
      end
      redirect_to template_records_path(template_id: @template.id), notice: t("notices.create_after")
    rescue => ex
      new
      render "new"
    end
  end

  #=== 登録データ編集画面
  #
  # GET /templates/1/records/1/edit
  #
  # 登録したデータの編集を行う画面
  #link:../captures/templates/records/edit.png
  def edit
    set_form_assigns
  end


  #=== 登録データ更新処理
  #
  # PATCH /templates/1/records/1
  #
  # データの更新処理を行う機能
  def update
    begin
      ActiveRecord::Base.transaction do
        @template_record.save_from_params!(params[:template_record], @template)
      end
      redirect_to template_records_path(template_id: @template.id), notice: t("notices.update_after")
    rescue => ex
      edit
      render "edit"
    end
  end

  #=== データ削除処理
  #
  # DELETE /templates/1/records/1
  #
  # データの削除処理を行う機能
  def destroy
    # アクセス制限はfilterでかかる
    if @template.id != @template_record.template_id
      return redirect_to template_records_path(template_id: @template.id), alert: t(".alerts.can_not_delete")
    end

    if @template_record.is_referenced?
      # 他のデータから参照されているとき
      return redirect_to template_records_path(template_id: @template.id), alert: t(".alerts.is_referenced")
    end

    begin
      ActiveRecord::Base.transaction do
        @template_record.destroy
      end
      flash[:notice] = t(".success")
    rescue
      flash[:alert] = t(".failed")
    end
    redirect_to template_records_path(template_id: @template.id)
  end


  #=== CSV一括登録画面
  #
  # GET /templates/1/records/import_csv_form
  #
  # CSVファイルからデータの一括登録を行う画面
  #link:../captures/templates/records/import_csv_form.png
  def import_csv_form
    @import_csv = ImportCSV.new
  end

  #=== CSV一括登録確認画面
  #
  # POST /templates/1/records/confirm_import_csv
  #
  # CSVファイルからデータの一括登録を行う際の確認画面
  #link:../captures/templates/records/confirm_import_csv.png
  def confirm_import_csv
    @import_csv = ImportCSV.new(csv: import_csv_params[:csv].try(:read),
                                user: current_user,
                                template: @template)

    if @import_csv.valid?
      render :confirm_import_csv
    else
      render :import_csv_form
    end
  end

  #
  #=== CSV一括登録処理
  #
  # POST /templates/1/records/import_csv
  #
  # アップロードしたCSVファイルからデータの一括登録処理を行う機能
  def import_csv
    @import_csv = ImportCSV.new(user: current_user, template: @template)

    if @import_csv.save
      redirect_to complete_import_csv_template_records_path(@template)
    else
      redirect_to import_csv_form_template_records_path(@template), alert: t('.failure')
    end
  end

  #
  #=== 選択されたCSVファイルの削除
  #
  # DELETE /templates/1/records/import_csv
  #
  def remove_csv_file
    ImportCSV.remove_csv_file(current_user.id, @template.id)

    redirect_to import_csv_form_template_records_path(@template)
  end

  #=== CSV一括登録完了画面
  #
  # GET /templates/1/records/complete_import_csv
  #
  # CSV一括登録の完了画面
  # 完了メッセージを表示する。
  #link:../captures/templates/records/complete_import_csv.png
  def complete_import_csv
  end


  #=== CSV出力
  #
  # GET /templates/1/records/download_csv
  #
  # 登録されているデータをCSV変換したものを出力する機能
  def download_csv
    respond_to do |format|
      format.csv{ send_data(@template.convert_records_csv, filename: "data.csv") }
    end
  end

  #=== RDF出力
  #
  # GET /templates/1/records/download_rdf
  #
  # 登録されているデータをRDF変換したものを出力する機能
  def download_rdf
    template_records = @template.template_records.order("template_records.id").includes([:user, {values: :content}])
    rdf = Sengu::Rdf::Builder.new(@template, template_records)
    send_data(rdf.to_rdf, filename: "rdf.xml")
  end

  #=== 入力内容のキーワード検索
  #
  # POST /templates/1/records/search_keyword
  #
  # 「登録内容の確認」ボタンを押下された場合にモーダル表示される画面。
  # キーワードに一致した者を表示する。
  #link:../captures/templates/records/search_keyword.png
  def search_keyword
    @element = Element.find(params[:element_id])
    @keywords = params[:keyword].split(" ") # スペース区切り
    if @keywords.size > 5
      @error = t(".there_are_many_keyword", count: 5)
    else
      tp_ids = @template.has_parent? ? [@template.id, @template.parent.id] : [@template.id]
      @content_lists = @keywords.map do |key|
        ElementValue::Line.includes(element_value: :template_record)
                          .references(:element_value)
                          .where("element_values.template_id IN (?)", tp_ids)
                          .where("element_values.element_id = ? AND value LIKE ?", @element.id, "%#{key}%")
      end
    end
  end


  #=== 要素毎の説明表示画面
  #
  # GET /templates/1/records/element_description
  #
  # データの登録画面等でテンプレート要素名の横に表示されるハテナマークを
  # クリックしたときに表示される要素の説明画面
  #link:../captures/templates/records/element_description.png
  def element_description
    @element = Element.find(params[:element_id])
    @item_number = params[:item_number]
    @conditions = @element.input_conditions
    render partial: "element_description"
  end

  #=== 関連データの検索画面
  #
  # POST /templates/1/records/element_relation_search_form
  #
  # テンプレート要素が他のテンプレートを参照している場合に、
  # 参照先のテンプレートのデータを選択する際の検索画面
  #link:../captures/templates/records/element_relation_search_form.png
  def element_relation_search_form
    @element_relation_content_search = ElementRelationContentSearch.new(element_id: params[:element_id])
    @item_number = params[:item_number]
    @selected_ids = params[:selected_ids] ? params[:selected_ids] : []
    render partial: "element_relation_search_form"
  end

  #=== 関連データの検索結果表示
  #
  # POST /templates/1/records/element_relation_search
  #
  # テンプレート要素が他のテンプレートを参照している場合に、
  # 参照先のテンプレートのデータを選択する際の検索処理、検索結果表示画面
  #link:../captures/templates/records/element_relation_search.png
  def element_relation_search
    @element_relation_content_search = ElementRelationContentSearch.new(params[:element_relation_content_search])
    values = @element_relation_content_search.search.to_a
    @values = Kaminari.paginate_array(values).page(params[:page]).per(5)
    if @element_relation_content_search.input_type.template?
      @source_element = @element_relation_content_search.element.source_element
    end
    @selected_id = params[:selected_id] if @element_relation_content_search.input_type.pulldown?
  end

  #=== 選択した関連データの表示
  #
  # GET /templates/1/records/1/display_relation_contents
  #
  # チェックボックスやプルダウン項目で選択しているデータを表示する画面
  #link:../captures/templates/records/display_relation_contents.png
  def display_relation_contents
    @element = Element.find(params[:element_id])
    records = @template_record.record_values_by_element(@element).select{|v|v.item_number.to_i == params[:item_number].to_i}.map{|v|v.content.try(:reference)}
    @records = Kaminari.paginate_array(records).page(params[:page]).per(5)

    klass = @element.source_type.constantize
    case klass.name
    when Template.name
      @relation_template = @element.source
      @source_element = @element.source_element
    when Vocabulary::Element.name
      @relation_template = klass.includes(:values).find(@element.source_id)
    end
  end

  #
  #=== ファイルアップロード機能でアップロードしたファイルをダウンロード
  def download_file
    @element_value = @template.element_values.find_by(id: params[:element_value_id], record_id: @template_record.id)
    @content = @element_value.try(:content)
    path = @content.try(:path)
    if params[:element_value_id] =~ /[^0-9]/ || @content.blank? || !File.exist?(path)
      return render nothing: true, status: 404
    end
    send_file(path, filename: @content.value)
  end

  #=== データ登録フォームの追加
  def add_form
    @index = params[:index].to_i
    @element = Element.find(params[:element_id])
  end

  #=== データ登録フォームをネームスペース毎に追加
  def add_namespace_form
    @item_number = params[:item_number].to_i
    @index = params[:index]
    @element = Element.find(params[:element_id])
    set_prefs_and_cities
  end

  #=== データ入力サンプル画面
  #
  # GET /templates/1/records/sample_field
  #
  # 作成したテンプレートをもとにデータの入力画面のサンプルを表示する
  #link:../captures/templates/records/sample_field.png
  def sample_field
    @template_record ||= @template.template_records.build
    set_form_assigns
  end

  private

    #=== フォームで使用するインスタンスのセット
    def set_form_assigns
      @elements = @template.all_elements.root.availables.includes(:input_type, :source)
      set_prefs_and_cities
    end

app/helpers/templates/records_helper.rb
module Templates::RecordsHelper
  #
  #=== 都道府県のセレクトを返す
  #
  def options_for_select_with_prefs(prefs, selected = "")
    list = prefs.map{|pre|[pre.name, pre.id]}
    options_for_select(list, selected)
  end

  #
  #=== 関連データのプルダウンを返す
  #
  def options_for_select_with_reference_values(element, selected = "")
    lists = element.selection_of_reference_values
    lists.unshift([t("shared.non_select"), ""])
    options_for_select(lists, selected.to_i)
  end

  #
  #=== 関連データのラジオボタンを返す
  #
  def reference_values_radio_button(element, field_name, selected = "", options = {})
    html = ""
    lists = element.selection_of_reference_values
    lists.unshift([t("shared.non_select"), ""])
    lists.each do |label, val|
      html += content_tag(:label, class: "radio-inline") do
        radio_button_tag( field_name, val, (selected == val), options) + label
      end
    end
    return raw html
  end

  #=== 追加ボタンタグ
  def add_button_tag(label = "")
    content_tag(:span, label , class: "glyphicon glyphicon-plus")
  end

  #=== 削除ボタンタグ
  def remove_button_tag(label = "")
    content_tag(:span, label, class: "glyphicon glyphicon-minus")
  end

  #
  #=== 入力フォームの追加ボタンを返す。
  def add_form_button(template, element, index, disabled = false)
    opts = {
      class: "btn btn-success add-form-button ajax-loading-display",
      method: :post,
      data: {
        "element-id" => element.id, "index" => index,
        "href" => add_form_template_records_path(template_id: template.id)
      }
    }
    opts.merge!("disabled" => "disabled") if disabled
    link_to(add_button_tag, "javascript:;", opts)
  end

  #
  #=== 入力フォームの削除ボタンを返す
  def remove_form_button(element_id, index)
    link_to(remove_button_tag, "javascript:;",
      {
        class: "btn btn-danger remove-form-button",
        data: {"remove-id" => "input_form_#{element_id}_#{index}"}
      }
    )
  end

  #
  #=== 必須入力を表すアイコンを表示
  def required_icon
    label = "（#{Element.human_attribute_name(:required)}）"
    content_tag(:strong, label, class: "text-danger")
  end

  #
  #=== ネームスペース単位で入力フォームを追加するボタン
  def add_namespace_form_button(template, element, item_number, index, disabled = false)
    opts = {
      class: "btn btn-success add-namespace-form-button ajax-loading-display",
      method: :post,
      data: {
        "element-id" => element.id, "index" => index,
        "item-number" => item_number,
        "href" => add_namespace_form_template_records_path(template_id: template.id)
      }
    }
    opts.merge!("disabled" => "disabled") if disabled
    link_to(add_button_tag, "javascript:;", opts)
  end

  #
  #=== ネームスペース毎の入力フォームの削除ボタンを返す
  def remove_namespace_form_button(element_id, item_number, index, disabled = false)
    opts = {
      class: "btn btn-danger remove-namespace-form-button",
      data: {"remove-id" => "namespace_field_#{element_id}_#{index}_#{item_number}"}
    }
    opts.merge!("disabled" => "disabled") if disabled
    link_to(remove_button_tag, "javascript:;", opts)
  end

  #
  #=== 時間のセレクトタグを設置
  def options_for_select_with_hours(selected = "")
    lists = (0..23).to_a.map{|n|[("%02d" % n) , n]}
    lists.unshift([t("shared.non_select"), ""])
    options_for_select(lists, (selected.blank? ? "" : selected.to_i))
  end

  #
  #=== 分のセレクトタグを設置
  def options_for_select_with_minutes(selected = "")
    lists = []
    n = 0
    while n < 60
      lists << n
      n += 5
    end
    lists = lists.map{|n|[("%02d" % n) , n]}
    lists.unshift([t("shared.non_select"), ""])
    options_for_select(lists, (selected.blank? ? "" : selected.to_i))
  end
end

app/views/templates/records/_display_relation_contents.html.erb
<div class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">
          <%
            case @element.source_type.constantize.name
            when Template.name
          %>
            <%= t('.template.title', template_name: relation_template.name) %>
          <% when Vocabulary::Element.name %>
            <%= t('.vocabulary.title', vocabulary_name: relation_template.name) %>
          <% end %>
        </h4>
      </div>
      <div class="modal-body" id="display_relation_contents-pagination">
        <%= render partial: "display_relation_contents_list", locals: {relation_template: relation_template, source_element: source_element, records: records} %>
      </div>

      <div class="modal-footer">
        <%= button_tag_with_icon t('shared.close'), type: 'button', class: "btn btn-warning", data: {dismiss: "modal"}, icon: 'remove-sign' %>
      </div>
    </div>
  </div>
</div>

app/views/templates/records/_element_relation_search_result_template.html.erb
<ul class="list-group">
  <% values.each.with_index(1) do |(r_id, vals), idx| %>
    <% value = r_id %>
    <% tr = vals.first.template_record %>
    <% item_number = vals.map(&:item_number).min %>
    <li class="list-group-item">
      <% if element.input_type.checkbox? %>
        <div class="checkbox">
          <label>
            <%= check_box_tag("content_ids[]", value, false, class: "remember-checkbox") %>
            <%= render partial: "record_value", locals: {
              values: vals, item_number: item_number,
              element: source_element, record: tr, template: @element_relation_content_search.element.source} %>
          </label>
        </div>
      <% else %>
        <% if @selected_id.to_i == value %>
          <span class="label label-success"><%= t(".selected") %></span>
        <% end %>
        <%= button_tag_with_icon t(".select"), class: "btn btn-primary pulldown_select_btn", data: {value: value}, icon: "plus-sign" %>
        <%= render partial: "record_value", locals: {
          values: vals, item_number: item_number,
          element: source_element, record: tr, template: @element_relation_content_search.element.source} %>
      <% end %>
    </li>
  <% end %>
</ul>

<% if element.input_type.pulldown? %>
<script>
  $(document).ready(function(){
    var hidden_id = '<%= "#element_#{@element_relation_content_search.element.id}_hidden" %>'
    $(".pulldown_select_btn").on("click", function(){
      var select_values_id = '#element<%= element.id %>_select_values'
      $(select_values_id).html('<%= t(".select_count") %> : ' + 1)
      var value = $(this).data("value")
      $(hidden_id).attr("value", value)
      $('#element_relation_search_form_modal').modal('hide')
      return false
    })
  })
</script>
<% end %>

app/views/templates/records/_form.html.erb
<%= render partial: "/templates/maps/shown_modal_script" %>
<%= error_messages_for(@template_record) %>

<% elements.each.with_index(1) do |element, index| %>
  <div class="row input-data-table">
    <% if element.namespace? %>
      <% if element.multiple_input?  %>
        <% element_values = @template_record.record_values(@template).select{|v|v.repeat_element_id == element.id}.group_by(&:item_number) %>
        <% if element_values.present?  %>
          <% element_values.each.with_index(1) do |(item_number, values), index| %>
            <div id="namespace_fields_<%= element.id %>_<%= index %>">
              <%= render partial: "/templates/records/namespace_form", locals: {element: element, element_values: values, item_number: item_number, index: index} %>
            </div>
          <% end %>
        <% else %>
          <div id="namespace_fields_<%= element.id %>_1">
            <%= render partial: "/templates/records/namespace_form", locals: {element: element, element_values: [], item_number: 1, index: 1} %>
          </div>
        <% end %>
      <% else %>
        <div id="namespace_fields_<%= element.id %>_1">
          <%= render partial: "/templates/records/namespace_form", locals: {element: element, element_values: element_values, item_number: 1, index: 1} %>
        </div>
      <% end %>
    <% else %>
      <% values = @template_record.record_values_by_element(element, @template).select{|v|v.item_number == 1} %>
      <%= render partial: "/templates/records/element_form", locals: {element: element, element_values: values, item_number: 1}  %>
    <% end %>
  </div>
<% end %>

<%= render partial: "/shared/map_script" %>

<script>
  // 都道府県セレクト変更時
  $(document).on("change", '.pref_id_select', function(e){
    var uniq_id = $(this).data("uniq_id")
    $.get('<%= main_app.search_city_id_select_template_maps_path %>', {uniq_id: uniq_id, pref_id: $(this).val()},  function(render_html){
      $("#city_select_" + uniq_id).html(render_html);
    });
  });


  // 検索ボタン押下時
  $(document).on("click", '.address_btn', function(e){
    var uniq_id = $(this).data("uniq_id")
    var pref_id = $("#pref_id_" + uniq_id).val()
    var city_id = $("#city_id_" + uniq_id).val()
    var address = $("#address_" + uniq_id).val()
    $.ajax({
      type: "post",
      url: "<%= main_app.search_address_location_template_maps_path %>",
      data: "uniq_id=" + uniq_id + "&pref_id=" + pref_id + "&city_id=" + city_id + "&address=" + address
    });
    return false
  });

  $(document).on("click", '[rel=ajax-popover]', function(e){
    var e=$(this);
    var field = $("#" + e.data("desc-field"))
    if (field.attr("data-popover-status") == "show"){
      field.attr("data-popover-status", "hide")
      field.popover('hide');
    }else{
      var element_name = e.data("element-name")
      var title = element_name + '<button id="' + field.attr("id") + '_desc_close" type="button" class="close pull-right" aria-hidden="true">&times;</button>'
      field.attr("data-popover-status", "show")
      //e.unbind('click');
      $.get(e.data('url'),function(d) {
        field.popover({title: title, content: d, html: true, placement: "bottom", trigger: "manual"}).popover('show');
      });
    }
  });

</script>

app/views/templates/records/_vocabulary_element_list.html.erb
<table class='table table-bordered table-striped'>
  <thead>
    <tr>
      <th><%= t('.no') %></th>
      <th><%= t('.vocabulary') %></th>
    </tr>
  </thead>

  <tbody>
    <% values.each.with_index(1) do |val, idx| %>
      <tr>
        <td><%= idx %></td>
        <td><%= val.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/templates/records/complete_import_csv.html.erb
<% content_for(:page_title){ page_title(template_name: @template.name) } %>
<% content_for(:wizard) do %>
  <%= render partial: "import_csv_step_wizard", locals: {current_action: :complete} %>
<% end %>
<br />

<%= alert_tag(type: :success){t(".complete_message")} %>

<%= link_to_with_icon(t(".back"), services_path, class: "btn btn-warning", icon: "circle-arrow-left") %>
<%= link_to_with_icon(t(".to_data_list"), template_records_path(@template), class: "btn btn-primary", icon: "list") %>

app/views/templates/records/confirm_import_csv.html.erb
<% content_for(:page_title){ page_title(template_name: @template.name) } %>

<% content_for(:wizard) do %>
  <%= render partial: "import_csv_step_wizard", locals: {current_action: :confirm} %>
<% end %>

<%= alert_tag(type: :info){t(".description")} %>

<% unless registrable = !@import_csv.records.any?{|r| r.errors.any?} %>
  <div class="panel-group" id="accordion">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#error-messages">
            <%= t('.exists_error') %>
          </a>
        </h4>
      </div>
      <div id="error-messages" class="panel-collapse collapse">
        <div class="panel-body">
          <%= alert_tag(type: :danger) do %>
            <ul>
              <% @import_csv.records.each do |record| %>
                <% if record.errors.any? %>
                  <li>
                    <%= link_to t('.row', line_number: record.line_numbers.join(',')), "#line-#{record.line_numbers.first}" %>
                    <ul>
                      <% record.errors.full_messages.uniq.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                    </ul>
                  </li>
                <% end %>
              <% end %>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <%= alert_tag(type: :success){t('.nothing_error')} %>
<% end %>

<%= form_for(@template, url: import_csv_template_records_path(@template), method: :post, multipart: true) do |f|%>
  <div class="table-responsive overflow">
    <table class="table table-bordered">
      <caption><%= t(".data_list") %></caption> <thead>
        <tr>
          <th style="white-space: nowrap;"><%= t(".line_number") %></th>
          <% @import_csv.header.each do |name| %>
            <th style="white-space: nowrap;"><%= name %></th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @import_csv.rows.each.each_with_index do |row, line_number| %>
          <% record = @import_csv.records.detect{|r| r.line_numbers.include?(line_number + 2) } %>
          <tr id="line-<%= line_number + 2 %>" class="odd gradeX <%= record && record.errors.any? ? 'danger' : '' %>">
            <td style="white-space: nowrap;"><%= line_number + 2 %></td>
            <% row.each_with_index do |v| %>
              <td><%= v %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= button_tag_with_icon t(".import"), class: "btn btn-primary loading-display", icon: "save", disabled: !registrable %>
  <%= link_to_with_icon t('.back'), import_csv_form_template_records_path, class: 'btn btn-warning', icon: 'circle-arrow-left' %>
<% end %>

app/views/templates/records/new.html.erb
<% content_for(:page_title){ page_title(template_name: @template.name) } %>

<% if @elements.present? %>

  <%= alert_tag(type: :info){t('.description', template_name: @template.name)} %>

  <%= form_for(@template_record, url: template_records_path(template_id: @template.id), html: {multipart: true, id: "content_form", class: "form-horizontal well"}) do |f| %>
    <%= render partial: "form", locals: {form: f, elements: @elements, record: @template_record} %>
    <%= button_tag_with_icon t("shared.new"), method: :post, class: "btn btn-primary", icon: "plus-sign" %>
    <%= link_to_with_icon(t(".back_to_list", template_name: @template.name), template_records_path(template_id: @template.id), class: "btn btn-warning", icon: "circle-arrow-left") %>
  <% end %>
<% else %>
  <%= alert_tag(type: :warning) do %>
    <% if current_user.editor? %>
      <%= t('.editor.nothing_elements_description', template_name: @template.name) %>
      <%= link_to_back(template_records_path(template_id: @template.id)) %>
    <% else %>
      <%= t('.manager.nothing_elements_description', template_name: @template.name) %>
      <%= link_to_back(template_records_path(template_id: @template.id)) %>
      <%= link_to_with_icon(t(".template_element_settings"), new_template_element_path(template_id: @template.id), class: 'btn btn-primary', icon: "edit") %>
    <% end %>
  <% end %>
<% end %>

app/views/templates/records/sample_field.js.erb
$("<%= j(render 'sample_field') %>").modal();