config/routes.rb
Sengu::Application.routes.draw do
  resources :services, except: [:show] do
    collection do
      post :search
    end

    member do
      get :template_list
    end
  end
  resources :templates, controller: "templates/templates", except: [:index, :show] do
    collection do
      post :element_relation_search_form
      post :element_relation_search

      get :change_order_form
      patch :change_order
    end

    member do
      get :data_select_upon_extension_form
      post :data_select_upon_extension
      post :data_select_upon_extension_preview
      get :download_csv_format     # CSVフォーマット出力
      get :download_description_pdf
    end

    resources :records, controller: "templates/records" do
      collection do
        get :import_csv_form      # CSV一括登録画面
        post :confirm_import_csv  # CSV一括登録確認
        post :import_csv          # CSV一括登録処理
        get :complete_import_csv  # CSV一括登録完了画面
        get :download_csv         # CSV出力
        get :download_rdf         # RDF出力

        post :search_keyword       # キーワード検索

        get :element_description # 項目の説明popover

        post :element_relation_search_form
        post :element_relation_search
        delete :remove_csv_file

        post :add_form
        post :add_namespace_form
        get :sample_field
      end

      member do
        get :display_relation_contents # 選択している関連データの表示
        get :download_file
      end
    end

    resources :elements, controller: "templates/elements", except: [:show, :index] do
      collection do
        get :show
        get :vocabulary_form
        get :other_form
        get :change_form
        get :select_other_element_form
        get :template_form
        get :sort
        patch :change_order
        get :values
        get :vocabulary_values
        get :show_elements
        get :edit_settings
        patch :update_settings
      end

      member do
        patch :move
      end
    end

    resources :settings, controller: "templates/settings", only: [] do
      collection do
        get :set_confirm_entries
        post :update_set_confirm_entries
        get :set_authority
        post :update_set_authority
      end

      member do
        get :edit_location_group
        patch :update_location_group # グループ編集
      end
    end
  end

  namespace :templates, as: :template do
    resources :maps, only: [] do
      collection do
        post :display_search # 住所検索地図表示
        get :display # 地図表示
        get :search_city_id_select # 市町村セレクトの都道府県きりかえ
        post :search_address_location # 住所検索
        get :load_content # 国土地理院の画像を表示するためのアクション
      end
    end
  end

  root to: 'services#index'

  devise_for :users, {
    controllers: {
      registrations: "users",
      sessions: "users/sessions"
    }
  }

  scope :admin, module: :admin do
    resources :regular_expressions

    namespace :vocabulary do
      resources :elements do
        resources :values, controller: "elements/values"
      end
    end
  end

  scope :user_maintenance, module: :user_maintenance do
    resources :sections do
      devise_scope :user do
        resources :users, controller: "sections/users" do
          collection do
            post :inherit_data
            get :inherit_data_form
            get :edit_password
            patch :update_password
          end
        end
      end

      resources :user_groups, controller: "sections/user_groups" do
        member do
          get :user_list
          get :template_list
          get :set_member
          post :search_member
          post :update_set_member
          delete :destroy_member
        end
      end
    end
  end

  mount Vdb::Engine => "/vdb"

end

app/models/vocabulary/element.rb
# == Schema Information
#
# Table name: vocabulary_elements
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#  from_vdb    :boolean          default(FALSE)
#

class Vocabulary::Element < ActiveRecord::Base
  has_many :elements, as: :source, class_name: "::Element"
  has_many :values, -> { order(:id) }, class_name: 'Vocabulary::ElementValue', dependent: :delete_all

  validates :name,
    presence: true,
    length: { maximum: 255 }

  accepts_nested_attributes_for :values

  #
  #=== Elementから実際に参照されるデータを返す。
  # Elementとsourceでリレーションしているクラスでは必ず必要なメソッド
  #==== 戻り値
  # * TemplateRecordリレーション
  def records_referenced_from_element
    self.values
  end

  def destroyable?
    !self.elements.exists?
  end

  #
  #=== RDFで使用するURLを返却する
  #
  def about_url_for_rdf
    Rails.application.routes.url_helpers.vocabulary_element_values_path(self)
  end
end

app/controllers/admin/vocabulary/elements/values_controller.rb
#
#== 語彙データ管理機能
#
class Admin::Vocabulary::Elements::ValuesController < ApplicationController
  include Concerns::AdminController
  before_action :set_element
  before_action :set_element_value, only: [:edit, :update, :destroy]

  add_breadcrumb I18n.t("admin.vocabulary.elements.index.title"), :vocabulary_elements

  #
  #=== 語彙データ内容設定画面
  #
  # GET /vocabulary/elements/:id/values/new
  #
  # 語彙データのコードリストの中身の値を設定する画面
  #
  #link:../captures/admin/vocabulary/elements/values/new.png
  def new
    @element_value = ::Vocabulary::ElementValue.new
  end

  #
  #=== 語彙データ内容作成
  #
  # POST /vocabulary/elements/:id/values
  #
  # 語彙データのコードリストの中身の値を作成する
  #
  def create
    @element_value = @element.values.build(vocabulary_element_value_params)

    if @element_value.save
      redirect_to new_vocabulary_element_value_path(@element), notice: t('.success')
    else
      render 'new'
    end
  end

  #
  #=== 語彙データ内容編集
  #
  # POST /vocabulary/elements/:id/values/:id/edit
  #
  # 語彙データのコードリストの中身の値を編集する
  #
  #link:../captures/admin/vocabulary/elements/values/edit.png
  def edit
  end

  #
  #=== 語彙データ内容更新
  #
  # PATCH /vocabulary/elements/:id/values/:id
  #
  # 語彙データのコードリストの中身の値を更新する
  #
  def update
    if @element_value.update(vocabulary_element_value_params)
      redirect_to new_vocabulary_element_value_path(@element), notice: t('.success')
    else
      render 'edit'
    end
  end

  #
  #=== 語彙データ内容削除
  #
  # DELETE /vocabulary/elements/:id/values/:id
  #
  # 語彙データのコードリストの中身の値を削除
  #
  def destroy
    @element_value.destroy
    redirect_to new_vocabulary_element_value_path(@element), notice: t('.success')
  end

private

  def set_element
    @element = ::Vocabulary::Element.find(params[:element_id])
  end

  def set_element_value
    @element_value = @element.values.find(params[:id])
  end

  def vocabulary_element_value_params
    params.require(:vocabulary_element_value).permit(:name)
  end
end

app/controllers/admin/vocabulary/elements_controller.rb
#
#== 語彙コードリストデータ管理機能
#
class Admin::Vocabulary::ElementsController < ApplicationController
  include Concerns::AdminController
  before_action :set_element, only: [:show, :edit, :update, :destroy]
  before_action :destroy_check, only: [:destroy]

  add_breadcrumb "I18n.t('admin.vocabulary.elements.index.title')", :vocabulary_elements, except: [:index], eval: true

  #
  #=== 語彙データ検索画面・一覧表示画面
  #
  # GET /vocabulary/elements/index
  #
  # 語彙データのコードリストの検索・一覧表示を行える
  #
  #link:../captures/vocabulary/elements/index.png
  def index
    @elements = ::Vocabulary::Element.all.order(:id)
  end

  #
  #=== 語彙データ詳細画面　
  #
  # GET /vocabulary/elements/:id
  #
  # 語彙データの詳細表示を行う
  #
  #link:../captures/vocabulary/elements/show.png
  def show
  end

  #
  #=== 語彙データ作成
  #
  # GET /vocabulary/elements/new
  #
  # 語彙データ(Vocabulary::Element)の作成を行う
  #
  #link:../captures/vocabulary/elements/new.png
  def new
    @element = ::Vocabulary::Element.new
  end

  #
  #=== 語彙データ保存
  #
  # POST /vocabulary/elements
  #
  # 語彙データ(Vocabulary::Element)の保存を行う
  #
  def create
    @element = ::Vocabulary::Element.new(vocabulary_element_params)

    if @element.save
      redirect_to new_vocabulary_element_value_path(@element), notice: t('.success')
    else
      render 'new'
    end
  end

  #
  #=== 語彙データ編集
  #
  # GET /vocabulary/elements/:id/edit
  #
  # 語彙データ(Vocabulary::Element)の編集を行う
  #
  #link:../captures/vocabulary/elements/edit.png
  def edit
  end

  #
  #=== 語彙データ更新
  #
  # PATCH /vocabulary/elements/:id
  #
  # 語彙データ(Vocabulary::Element)の更新を行う
  #
  def update
    if @element.update(vocabulary_element_params)
      redirect_to vocabulary_elements_path, notice: t('.success')
    else
      render 'edit'
    end
  end

  #
  #=== 語彙データ削除
  #
  # DELETE /vocabulary/elements/:id
  #
  # 語彙データ(Vocabulary::Element)の削除を行う
  #
  def destroy
    @element.destroy

    redirect_to vocabulary_elements_path, notice: t('.success')
  end

private

  def set_element
    @element = ::Vocabulary::Element.find(params[:id])
  end

  def vocabulary_element_params
    params.require(:vocabulary_element).permit(:name, :description)
  end

  def destroy_check
    return redirect_to vocabulary_elements_path, alert: t('.failure_destroy') unless @element.destroyable?
  end
end

app/controllers/templates/elements_controller.rb
#
#=== テンプレートエレメントの管理を行うコントローラー
#
# テンプレートが属するサービスの所属の管理者・所属の管理者のみがアクセスできる
#
class Templates::ElementsController < ApplicationController
  include Concerns::TemplatesController

  before_action :template_operator_check
  before_action :set_element, only: [:edit, :update, :destroy, :move]
  before_action :destroy_check, only: [:destroy]

  layout "template_elements", only: [:show_elements, :new, :edit, :create, :update, :edit_settings, :update_settings]

  #
  #=== テンプレート編集画面
  #
  # GET /templates/1/elements/new
  #
  # テンプレートのカスタマイズ画面
  #
  #link:../captures/templates/elements/new.png
  def new
    @element = Element.new(input_type_id: InputType.find_line.try(:id))
  end

  #
  #=== テンプレート要素編集画面
  #
  # GET /templates/1/elements/1/edit
  #
  # テンプレート要素編集画面
  #
  #link:../captures/templates/elements/edit.png
  def edit
  end

  #
  #=== テンプレート要素の詳細表示画面
  #
  # GET /templates/1/elements/1
  #
  # テンプレート要素の詳細表示を行う
  # 子要素の表示や、並び替えを行うことが出来る
  #
  #link:../captures/templates/elements/show.png
  def show
    respond_to do |format|
      format.js{ @element = Element.find(params[:id]) if params[:id].present? }
    end
  end

  #
  #=== テンプレート要素の作成
  #
  # POST /templates/1/elements/
  #
  # テンプレート要素の作成を行う
  #
  def create
    @element = @template.elements.build(element_params)

    if @element.save
      redirect_to show_elements_template_elements_path(params[:template_id]), notice: t('.success')
    else
      render :new
    end
  end

  #
  #=== テンプレート要素の更新
  #
  # PATCH /templates/1/elements/1
  #
  # テンプレート要素の更新を行う
  #
  def update
    if @element.update(element_params)
      redirect_to show_elements_template_elements_path(params[:template_id]), notice: t('.success')
    else
      render :edit
    end
  end

  #
  #=== テンプレート要素の削除
  #
  # DELETE /templates/1/elements/1
  #
  # テンプレート要素の削除を行う
  #
  def destroy
    @element.destroy

    redirect_to show_elements_template_elements_path(params[:template_id]), notice: t('.success')
  end

  #
  #=== テンプレートフォームの切り替え
  #
  # GET /templates/1/elements/change_template
  #
  # 語彙データを使用するべき入力タイプが選択された場合に、
  # インラインでフォームを切り替える
  #
  def change_form
    respond_to do |format|
      format.js do
        if params[:id].present?
          @element = Element.find(params[:id])
        else
          @element = Element.new(input_type_id: InputType.find_line.try(:id))
        end
        @input_type = InputType.find(params[:input_type_id])
        @target = params[:target] || "#change-for-input-type-form"
      end
    end
  end


  #
  #=== データ入力時表示項目のプルダウンの切り替え
  #
  # GET /templates/1/elements/select_other_element_form
  #
  # テンプレートを参照するさいに表示する項目を選択するフォームをrenderする
  #
  def select_other_element_form
    respond_to do |format|
      format.js do
        @reference_template = Template.find(params[:reference_template_id])
        @element = @reference_template.elements.find_by(id: params[:id]) if params[:id].present?
        @target = params[:target] || "#select-other-element"
        @dir = params[:dir] || "forms"
      end
    end
  end

  #
  #=== テンプレート要素の移動
  #
  # PATCH /templates/1/elements/1/move
  #
  # テンプレート要素の移動を行う
  # 失敗した場合は、失敗した際のメッセージを返す
  #
  def move
    respond_to do |format|
      format.json do
        if @element.update(parent_id: element_params_as_move[:parent_id])
          render json: { result: true }
        else
          render json: { result: false, messages: @element.errors.full_messages }
        end
      end
    end
  end

  #
  #=== テンプレート要素の順番変更
  #
  # PATCH /templates/1/elements/1/change_order
  #
  # テンプレート要素の順番変更を行う
  #
  def change_order
    respond_to do |format|
      format.js do
        @result = Element.change_order(element_params_as_change_order[:display_number_ids])
      end
    end
  end

  #
  #=== 特定のテンプレート、特定の項目に対するelement_valuesを返す
  #
  # GET /templates/1/elements/1/values
  #
  # 項目の入力データを表示する
  #
  def values
    respond_to do |format|
      format.js do
        template_record_ids = @template.all_records.pluck(:id)
        @element = Element.find(params[:element_id])
        @element_values = ElementValue.where(record_id: template_record_ids, element_id: @element.id)
      end
    end
  end

  #=== 指定されたコードリストの内容を表示する
  #
  # GET /templates/1/elements/1/vocabulary_values
  #
  # 項目の入力データを表示する
  #
  def vocabulary_values
    respond_to do |format|
      format.js do
        @vocabulary_element = Vocabulary::Element.find(params[:vocabulary_element_id])
      end
    end
  end


  #
  #=== 項目一覧画面
  #
  # GET /templates/1/elements/new
  #
  # テンプレートに属する項目一覧画面
  #
  #link:../captures/templates/elements/show_elements.png
  def show_elements
  end

  #
  #=== 項目一括設定画面
  #
  # GET /templates/1/elements/edit_settings
  #
  # テンプレートに属する項目一括設定画面
  #
  #link:../captures/templates/elements/edit_settings.png
  def edit_settings
    @template = Template.where(id: params[:template_id]).includes(:elements => [{:children => :input_type}, :input_type]).first
    @flat_display_numbers = @template.calculate_flat_display_numbers
  end

  #
  #=== 項目一括更新
  #
  # PATCH /templates/1/elements/update_settings
  #
  # テンプレートに属する項目一括更新
  def update_settings
    # NOTE: templateに対する更新に見えるが、実際はtemplateが持つelementsを更新している。
    #       実際の更新対象がelementsのみなので、elements_controllerにアクションをもたせている。
    @template = Template.where(id: params[:template_id]).includes(:elements => [{:children => :input_type}, :input_type]).first
    @template.attributes = element_params_as_settings
    if @template.save
      redirect_to show_elements_template_elements_path(@template), notice: t('.success')
    else
      @flat_display_numbers = @template.calculate_flat_display_numbers
      render :edit_settings
    end
  end

  private

    def set_element
      @element = @template.elements.find(params[:id])
    end

    def element_params
      params.require(:element).permit(
        :name,
        :regular_expression_id,
        :input_type_id,
        :max_digit_number,
        :min_digit_number,
        :description,
        :data_example,
        :required,
        :unique,
        :display,
        :source_id,
        :source_element_id,
        :multiple_input,
        :available,
        :publish,
        :data_input_way,
      )
    end

    def element_params_as_move
      params[:element].permit(:parent_id)
    end

    def element_params_as_change_order
      params.require(:element).permit(display_number_ids: [])
    end

    def element_params_as_settings
      params.require(:template).permit(elements_attributes: [:id, :name, :input_type_id, :required, :unique, :available, :display, :source_id, :source_element_id, :data_input_way])
    end

    def destroy_check
      unless @element.destroyable?
        return redirect_to show_elements_template_elements_path(params[:template_id]), alert: t('.failure_destroy')
      end
    end
end

app/helpers/templates/elements_helper.rb
module Templates::ElementsHelper

  #
  #=== InputTypeによって、表示するフォームを切り替える
  #
  def render_form_with_input_type(template, element, input_type, options = {})
    dir = options.delete(:dir) || "forms"
    locals = {input_type: input_type, template: template, element: element}
    locals.merge!(child_index: options.delete(:child_index)) if options[:child_index]
    if input_type.present?
      if input_type.vocabulary?
        return render partial: "templates/elements/#{dir}/vocabulary_form", locals: locals
      elsif input_type.template?
        return render partial: "templates/elements/#{dir}/template_select_form", locals: locals
      end
    end
    render partial: "templates/elements/#{dir}/other_form", locals: locals
  end

  #
  #=== elementsを一括で更新する際のエラーメッセージの表示
  #
  def error_messages_for_nested_elements(elements)
    messages = elements.map do |element|
      element.errors.full_messages.map{ |m| element.full_name + " " + m }
    end.flatten.compact
    render_error_messages(messages)
  end

  #
  #=== 関連データの入力方法のセレクトを表示する。
  #
  #==== 引数
  # * input_type - フォームで選択中の入力タイプ
  # * selected - デフォルトの選択値
  def options_for_select_with_data_input_ways(input_type, selected = "")
    if diws = Element::DATA_INPUT_WAYS[input_type.name.to_sym]
      lists = diws.map{|k,v|[t("element.data_input_way_label.#{k}"), v]}

      options_for_select(lists, selected.to_s)
    end
  end
end

app/views/templates/elements/forms/_other_form.html.erb
<% if input_type.blank? || input_type.limitable? %>
  <%= render "templates/elements/forms/elements/regular_expression_form", input_type: input_type, element: element %>
  <%= render "templates/elements/forms/elements/max_digit_number_form", input_type: input_type, element: element %>
  <%= render "templates/elements/forms/elements/min_digit_number_form", input_type: input_type, element: element %>
<% end %>

<%= render "templates/elements/forms/elements/description_form", element: element %>
<%= render "templates/elements/forms/elements/data_example_form", element: element unless input_type.upload_file? %>
<%= render "templates/elements/forms/elements/required_form", element: element %>
<%= render "templates/elements/forms/elements/unique_form", element: element unless input_type.upload_file? %>

<script>
  $(document).ready(function(){
    $('.static-tooltip-description').tooltip()
  })
</script>

app/views/templates/elements/forms/_template_select_form.html.erb
<% if template.service_id.present? %>
  <% templates = template.same_service_templates(false).displayables(current_user).order(:display_number).to_a %>
  <div class="form-group">
    <%= label_tag :element_source_id, t('.use_template'), class: 'col-lg-2 control-label' %>
    <div class="col-lg-5">
      <%= select_tag :element_source_id,
        options_for_select(templates.map{|t| [t.name, t.id]}, element.try(:source_id)),
        name: 'element[source_id]',
        class: 'form-control vocabulary-select static-tooltip-description',
        data: {
          toggle: "tooltip",
          placement: "top",
          'original-title' => t('.source_id_title')
        }
      %>
    </div>
  </div>

  <div id="select-other-element">
    <% source_template = element.try(:input_type_template?) ? element.source : nil %>
    <%= render '/templates/elements/forms/elements/source_element_id_select_form', template: source_template.blank? ? templates.first : source_template, element: element %>
  </div>

  <%= render "templates/elements/forms/elements/data_input_way_form", element: element, input_type: input_type %>
  <%= render "templates/elements/forms/elements/description_form", element: element %>
  <%= render "templates/elements/forms/elements/data_example_form", element: element %>
  <%= render "templates/elements/forms/elements/required_form", element: element %>
  <%= render "templates/elements/forms/elements/unique_form", element: element %>


  <script>
    $(document).ready(function(){
      $('.static-tooltip-description').tooltip()

      $('.data-confirm').on('click', function(){
        source_id = $('#element_source_id').val();
        if (source_id){
          window.open('/templates/' + $('#element_source_id').val() + '/records/');
        }
        return false;
      })

      $('#element_source_id').on('change', function(){
        $.get("<%= select_other_element_form_template_elements_path(template, format: :js) %>", {
          id: "<%= element.try(:id) %>",
          reference_template_id: $(this).val()
        });
      })
    })
  </script>
<% end %>

app/views/templates/elements/forms/_vocabulary_form.html.erb
<div class="form-group">
  <%= label_tag :element_source_id, t('.use_vocabulary'), class: 'col-lg-2 control-label' %>
  <div class="col-lg-5">
    <% v_els = Vocabulary::Element.pluck(:name, :id) %>
    <%= select_tag :element_source_id, options_for_select(v_els, element.try(:source_id)), name: 'element[source_id]', class: 'form-control vocabulary-select static-tooltip-description', data: {toggle: "tooltip", placement: "top", 'original-title' => t('.source_id_title')} %>
    <%= link_to_with_icon t('.data_confirm'), '#', class: 'btn btn-primary btn-sm data-confirm', remote: true if v_els.present? %>
  </div>
</div>

<%= render "templates/elements/forms/elements/data_input_way_form", element: element, input_type: input_type %>
<%= render "templates/elements/forms/elements/description_form", element: element %>
<%= render "templates/elements/forms/elements/data_example_form", element: element %>
<%= render "templates/elements/forms/elements/required_form", element: element %>
<%= render "templates/elements/forms/elements/unique_form", element: element %>

<script>
  $(document).ready(function(){
    $('.static-tooltip-description').tooltip()

    $('#element_source_id').on('change load', function(){
      $('.data-confirm').attr('href', '<%= vocabulary_values_template_elements_path(template) %>' + '?vocabulary_element_id=' + $(this).val())
    }).trigger('change');
  })
</script>