config/routes.rb
Sengu::Application.routes.draw do
  resources :services, except: [:show] do
    collection do
      post :search
    end

    member do
      get :template_list
    end
  end
  resources :templates, controller: "templates/templates", except: [:index, :show] do
    collection do
      post :element_relation_search_form
      post :element_relation_search

      get :change_order_form
      patch :change_order
    end

    member do
      get :data_select_upon_extension_form
      post :data_select_upon_extension
      post :data_select_upon_extension_preview
      get :download_csv_format     # CSVフォーマット出力
      get :download_description_pdf
    end

    resources :records, controller: "templates/records" do
      collection do
        get :import_csv_form      # CSV一括登録画面
        post :confirm_import_csv  # CSV一括登録確認
        post :import_csv          # CSV一括登録処理
        get :complete_import_csv  # CSV一括登録完了画面
        get :download_csv         # CSV出力
        get :download_rdf         # RDF出力

        post :search_keyword       # キーワード検索

        get :element_description # 項目の説明popover

        post :element_relation_search_form
        post :element_relation_search
        delete :remove_csv_file

        post :add_form
        post :add_namespace_form
        get :sample_field
      end

      member do
        get :display_relation_contents # 選択している関連データの表示
        get :download_file
      end
    end

    resources :elements, controller: "templates/elements", except: [:show, :index] do
      collection do
        get :show
        get :vocabulary_form
        get :other_form
        get :change_form
        get :select_other_element_form
        get :template_form
        get :sort
        patch :change_order
        get :values
        get :vocabulary_values
        get :show_elements
        get :edit_settings
        patch :update_settings
      end

      member do
        patch :move
      end
    end

    resources :settings, controller: "templates/settings", only: [] do
      collection do
        get :set_confirm_entries
        post :update_set_confirm_entries
        get :set_authority
        post :update_set_authority
      end

      member do
        get :edit_location_group
        patch :update_location_group # グループ編集
      end
    end
  end

  namespace :templates, as: :template do
    resources :maps, only: [] do
      collection do
        post :display_search # 住所検索地図表示
        get :display # 地図表示
        get :search_city_id_select # 市町村セレクトの都道府県きりかえ
        post :search_address_location # 住所検索
        get :load_content # 国土地理院の画像を表示するためのアクション
      end
    end
  end

  root to: 'services#index'

  devise_for :users, {
    controllers: {
      registrations: "users",
      sessions: "users/sessions"
    }
  }

  scope :admin, module: :admin do
    resources :regular_expressions

    namespace :vocabulary do
      resources :elements do
        resources :values, controller: "elements/values"
      end
    end
  end

  scope :user_maintenance, module: :user_maintenance do
    resources :sections do
      devise_scope :user do
        resources :users, controller: "sections/users" do
          collection do
            post :inherit_data
            get :inherit_data_form
            get :edit_password
            patch :update_password
          end
        end
      end

      resources :user_groups, controller: "sections/user_groups" do
        member do
          get :user_list
          get :template_list
          get :set_member
          post :search_member
          post :update_set_member
          delete :destroy_member
        end
      end
    end
  end

  mount Vdb::Engine => "/vdb"

end

app/views/shared/_breadcrumbs.html.erb
<% if elements.present? %>
  <ol class="breadcrumb">
    <% elements.each do |element| %>
      <li>
        <% path = builder.compute_path(element) %>
        <% name = builder.compute_name(element) %>
        <%= link_to_if(path.present?, name, path) %>
      </li>
    <% end %>
    <li><%= content_for?(:page_title) ? yield(:page_title) : page_title %></li>
  </ol>
<% end %>

app/views/shared/_map_script.html.erb
<%= javascript_include_tag "OpenLayers-2.13.1/OpenLayers.js" %>

app/views/shared/_search_location_script.js.erb
// 都道府県セレクト変更時
$(".pref_id_select").bind("change", function(){
  var vn_name = $(this).attr("data-prefix")
  $.get('<%= search_city_id_select_maps_path %>', {variable_name: vn_name, pref_id: $(this).val()},  function(render_html){
    $("#" + vn_name + "_city_select").html(render_html);
  });
});


// 検索ボタン押下時
$('.address_btn').click(function(e) {
  var vn_name = $(this).attr("data-prefix")
  var pref_id = $("#" + vn_name + "_pref_id").val()
  var city_id = $("#" + vn_name + "_city_id").val()
  var address = $("#" + vn_name + "_address").val()
  $.ajax({
    type: "post",
    url: "<%= search_address_location_maps_path %>",
    data: "variable_name=" + vn_name + "&pref_id=" + pref_id + "&city_id=" + city_id + "&address=" + address
  });
  return false
});